### ISSUE TITLE
option to disable autoconnect wallets

### ISSUE THREAD

**Issue by ashish-pcode** [lidofinance/lido-js-sdk#66] opened 2022-08-16 11:24 UTC
Hi,
I was trying to use the lido-js-sdk for wallet connection, I'm facing the issue when both metamask and coinbase wallet extensions are installed in the browser. Coinbase pops up on every reload. 
Can we have an option of disabling autoconnect feature?

https://github.com/lidofinance/lido-js-sdk/blob/main/packages/web3-react/README.md#auto-connect

@alx-khramov @avsetsin

**Comment by alx-khramov** [comment] 2022-08-16 12:48
Hi, @ashish-pcode 
It is possible, but are you sure? Without autoconnect a wallet will disconnect really often.
Maybe the issue can be fixed by some better way than disabling autoconnect?
For example, https://stake.lido.fi/ uses `lido-js-sdk/web3-react`, but I'm not able to reproduce your issue using our widget.
Not sure what is the reason for this issue. Coinbase and MetaMask wallets are trying to use the same `window.ethereum` object, but Coinbase overrides MetaMask. But they use different connectors: WalletLink for Coinbase against EIP-1193 (injected).
I checked the [Coinbase docs](https://docs.cloud.coinbase.com/wallet-sdk/docs), and it looks like our Coinbase-related code is a bit outdated. They changed how the wallet works along with other wallets, so the autoconnect feature stopped to work with Coinbase when the extension is installed with MetaMask.
I plan to update our code for Coinbase in the nearest future, so it can possibly fix the issue.

**Comment by ashish-pcode** [comment] 2022-08-16 13:05
Thanks for the detailed explanation @alx-khramov
I have attached the screenshot on my https://stake.lido.fi/, this is when I don't have metamask or coinbase installed but not connected to the website. 

<img width="1680" alt="Screenshot 2022-08-16 at 6 32 24 PM" src="https://user-images.githubusercontent.com/84492996/184886138-28fa0632-04ff-4521-9ddf-b6a7181029a5.png">

**Comment by alx-khramov** [comment] 2022-08-16 13:14
@ashish-pcode Is this Coinbase Wallet window opens by itself or did you click "Connect wallet => Coinbase" buttons to open it? The behavior on the screenshot looks expected for me, what am I missing?

**Comment by ashish-pcode** [comment] 2022-08-16 13:22
@alx-khramov it opens up by itself on every reload. Just refreshing the page opens up the pop.

**Comment by alx-khramov** [comment] 2022-08-16 13:44
@ashish-pcode okay, I see, thank you for reporting this. I will look how I can fix it.

**Comment by ashish-pcode** [comment] 2022-08-16 13:59
@alx-khramov sounds good, feel free to close the issue.

**Comment by alx-khramov** [comment] 2022-08-23 11:54
@ashish-pcode Hi! This PR #67 probably fixes the issue.

**Closed by alx-khramov** 2022-08-23 11:54 UTC
